-- Vibe Code Tracker Database Schema
-- Run this in your Supabase SQL editor

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create entries table only if it doesn't exist
CREATE TABLE IF NOT EXISTS entries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz DEFAULT now(),
  type text NOT NULL CHECK (type IN ('win', 'problem', 'money', 'avoidance')),
  content text NOT NULL,
  user_id uuid -- optional for v1, can be null
);

-- Modify entries table to support new types
ALTER TABLE entries 
  DROP CONSTRAINT IF EXISTS entries_type_check;

ALTER TABLE entries 
  ADD CONSTRAINT entries_type_check 
  CHECK (type IN (
    'win', 'problem', 'money', 'avoidance',
    -- Emotional/Mental
    'energy', 'mood', 'sleep',
    -- Habits/Health
    'workout', 'food', 'substance',
    -- Relationship
    'connection', 'conflict',
    -- Work/Productivity
    'focus', 'distraction', 'procrastination',
    -- Learning/Growth
    'learn', 'insight'
  ));

-- Add metadata column for structured data (energy scores, ratings) if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'entries' AND column_name = 'metadata') THEN
        ALTER TABLE entries ADD COLUMN metadata jsonb DEFAULT '{}'::jsonb;
    END IF;
END $$;

-- Weekly reports table
CREATE TABLE IF NOT EXISTS weekly_reports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  week_start date NOT NULL,
  summary text,
  patterns text,
  strategy text,
  drop_list text, -- things to stop doing
  created_at timestamptz DEFAULT now()
);

-- New table for check-ins (bundled entries)
CREATE TABLE IF NOT EXISTS checkins (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz DEFAULT now(),
  energy_score int CHECK (energy_score BETWEEN 1 AND 10),
  win_today text,
  avoided_today text,
  mood text,
  grateful_for text,
  user_id uuid
);

-- New table for pattern alerts
CREATE TABLE IF NOT EXISTS pattern_alerts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz DEFAULT now(),
  alert_type text NOT NULL, -- 'streak', 'threshold', 'absence'
  category text NOT NULL, -- 'workout', 'energy', 'win', etc.
  message text NOT NULL,
  severity text DEFAULT 'warning', -- 'info', 'warning', 'critical'
  dismissed_at timestamptz,
  user_id uuid
);

-- New table for conversation state (for multi-step Telegram flows)
CREATE TABLE IF NOT EXISTS conversation_state (
  chat_id bigint PRIMARY KEY,
  state text NOT NULL, -- 'awaiting_checkin_energy', 'awaiting_checkin_win', etc.
  data jsonb DEFAULT '{}'::jsonb,
  updated_at timestamptz DEFAULT now()
);

-- New table for chart data (generated by Gemini to avoid token overuse)
CREATE TABLE IF NOT EXISTS chart_data (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  chart_type text NOT NULL, -- 'entry_volume', 'energy_timeline', 'category_distribution', etc.
  period text NOT NULL, -- 'daily', 'weekly', 'monthly'
  data jsonb NOT NULL, -- Chart data points generated by Gemini
  generated_at timestamptz DEFAULT now(),
  expires_at timestamptz DEFAULT (now() + interval '24 hours'), -- Cache for 24 hours
  user_id uuid
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_entries_created_at ON entries(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_entries_type ON entries(type);
CREATE INDEX IF NOT EXISTS idx_weekly_reports_week_start ON weekly_reports(week_start DESC);
CREATE INDEX IF NOT EXISTS idx_checkins_created_at ON checkins(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pattern_alerts_created_at ON pattern_alerts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pattern_alerts_dismissed ON pattern_alerts(dismissed_at) WHERE dismissed_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_chart_data_type_period ON chart_data(chart_type, period);
CREATE INDEX IF NOT EXISTS idx_chart_data_expires ON chart_data(expires_at);

-- RLS Policies (public for v1 - single user)
-- Enable RLS
DO $$ BEGIN
    ALTER TABLE entries ENABLE ROW LEVEL SECURITY;
EXCEPTION WHEN others THEN
    -- RLS might already be enabled, continue
END $$;

DO $$ BEGIN
    ALTER TABLE weekly_reports ENABLE ROW LEVEL SECURITY;
EXCEPTION WHEN others THEN
    -- RLS might already be enabled, continue
END $$;

DO $$ BEGIN
    ALTER TABLE checkins ENABLE ROW LEVEL SECURITY;
EXCEPTION WHEN others THEN
    -- RLS might already be enabled, continue
END $$;

DO $$ BEGIN
    ALTER TABLE pattern_alerts ENABLE ROW LEVEL SECURITY;
EXCEPTION WHEN others THEN
    -- RLS might already be enabled, continue
END $$;

DO $$ BEGIN
    ALTER TABLE conversation_state ENABLE ROW LEVEL SECURITY;
EXCEPTION WHEN others THEN
    -- RLS might already be enabled, continue
END $$;

DO $$ BEGIN
    ALTER TABLE chart_data ENABLE ROW LEVEL SECURITY;
EXCEPTION WHEN others THEN
    -- RLS might already be enabled, continue
END $$;

-- Public access for v1 (replace with auth policies later)
DO $$ BEGIN
    CREATE POLICY "Allow all access to entries" ON entries
      FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN others THEN
    -- Policy might already exist, continue
END $$;

DO $$ BEGIN
    CREATE POLICY "Allow all access to weekly_reports" ON weekly_reports
      FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN others THEN
    -- Policy might already exist, continue
END $$;

DO $$ BEGIN
    CREATE POLICY "Allow all access to checkins" ON checkins
      FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN others THEN
    -- Policy might already exist, continue
END $$;

DO $$ BEGIN
    CREATE POLICY "Allow all access to pattern_alerts" ON pattern_alerts
      FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN others THEN
    -- Policy might already exist, continue
END $$;

DO $$ BEGIN
    CREATE POLICY "Allow all access to conversation_state" ON conversation_state
      FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN others THEN
    -- Policy might already exist, continue
END $$;

DO $$ BEGIN
    CREATE POLICY "Allow all access to chart_data" ON chart_data
      FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN others THEN
    -- Policy might already exist, continue
END $$;

-- Cron jobs (only if pg_cron extension is enabled)
-- Note: pg_cron may not be available in all Supabase plans
DO $$
BEGIN
    -- Check if cron schema exists (pg_cron extension)
    IF EXISTS (SELECT 1 FROM information_schema.schemata WHERE schema_name = 'cron') THEN

        -- Weekly cron job (configure in Supabase dashboard or run this)
        -- Note: Replace 'your-app.vercel.app' with your actual Vercel domain
        -- This runs every Sunday at 8pm UTC
        BEGIN
            -- Try to unschedule first in case it exists
            PERFORM cron.unschedule('weekly-review-trigger');
        EXCEPTION WHEN others THEN
            -- Job might not exist, continue
        END;

        PERFORM cron.schedule(
          'weekly-review-trigger',
          '0 20 * * 0',
          $cron_sql$
          SELECT net.http_post(
            url := 'https://ramavarma-thampuran-ai.vercel.app/api/weekly-review',
            headers := '{"Content-Type": "application/json", "Authorization": "Bearer YOUR_SECRET_KEY"}'::jsonb,
            body := '{}'::jsonb
          ) AS request_id;
          $cron_sql$
        );

        -- Daily pattern detection cron job (runs every day at 8pm UTC)
        BEGIN
            -- Try to unschedule first in case it exists
            PERFORM cron.unschedule('pattern-detection');
        EXCEPTION WHEN others THEN
            -- Job might not exist, continue
        END;

        PERFORM cron.schedule(
          'pattern-detection',
          '0 20 * * *',
          $cron_sql$
          SELECT net.http_post(
            url := 'https://ramavarma-thampuran-ai.vercel.app/api/pattern-detection',
            headers := '{"Content-Type": "application/json"}'::jsonb
          ) AS request_id;
          $cron_sql$
        );

        -- Daily chart data generation cron job (runs every day at 6am UTC)
        BEGIN
            -- Try to unschedule first in case it exists
            PERFORM cron.unschedule('chart-data-generation');
        EXCEPTION WHEN others THEN
            -- Job might not exist, continue
        END;

        PERFORM cron.schedule(
          'chart-data-generation',
          '0 6 * * *',
          $cron_sql$
          SELECT net.http_post(
            url := 'https://ramavarma-thampuran-ai.vercel.app/api/chart-data/generate',
            headers := '{"Content-Type": "application/json"}'::jsonb
          ) AS request_id;
          $cron_sql$
        );

        RAISE NOTICE 'Cron jobs scheduled successfully';

    ELSE
        RAISE NOTICE 'pg_cron extension not available. Cron jobs will not be scheduled. You can set them up manually in the Supabase dashboard or contact support to enable pg_cron.';
    END IF;
END $$;

-- Cron job management (only available if pg_cron is enabled)
-- View cron jobs (if available)
-- SELECT * FROM cron.job;

-- Unschedule if needed (if available)
-- SELECT cron.unschedule('weekly-review-trigger');
-- SELECT cron.unschedule('pattern-detection');
-- SELECT cron.unschedule('chart-data-generation');
