-- Vibe Code Tracker Database Schema
-- Run this in your Supabase SQL editor

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Entries table
CREATE TABLE entries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz DEFAULT now(),
  type text NOT NULL CHECK (type IN ('win', 'problem', 'money', 'avoidance')),
  content text NOT NULL,
  user_id uuid -- optional for v1, can be null
);

-- Modify entries table to support new types
ALTER TABLE entries 
  DROP CONSTRAINT IF EXISTS entries_type_check;

ALTER TABLE entries 
  ADD CONSTRAINT entries_type_check 
  CHECK (type IN (
    'win', 'problem', 'money', 'avoidance',
    -- Emotional/Mental
    'energy', 'mood', 'sleep',
    -- Habits/Health
    'workout', 'food', 'substance',
    -- Relationship
    'connection', 'conflict',
    -- Work/Productivity
    'focus', 'distraction', 'procrastination',
    -- Learning/Growth
    'learn', 'insight'
  ));

-- Add metadata column for structured data (energy scores, ratings)
ALTER TABLE entries 
  ADD COLUMN metadata jsonb DEFAULT '{}'::jsonb;

-- Weekly reports table
CREATE TABLE weekly_reports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  week_start date NOT NULL,
  summary text,
  patterns text,
  strategy text,
  drop_list text, -- things to stop doing
  created_at timestamptz DEFAULT now()
);

-- New table for check-ins (bundled entries)
CREATE TABLE checkins (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz DEFAULT now(),
  energy_score int CHECK (energy_score BETWEEN 1 AND 10),
  win_today text,
  avoided_today text,
  mood text,
  grateful_for text,
  user_id uuid
);

-- New table for pattern alerts
CREATE TABLE pattern_alerts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz DEFAULT now(),
  alert_type text NOT NULL, -- 'streak', 'threshold', 'absence'
  category text NOT NULL, -- 'workout', 'energy', 'win', etc.
  message text NOT NULL,
  severity text DEFAULT 'warning', -- 'info', 'warning', 'critical'
  dismissed_at timestamptz,
  user_id uuid
);

-- New table for conversation state (for multi-step Telegram flows)
CREATE TABLE conversation_state (
  chat_id bigint PRIMARY KEY,
  state text NOT NULL, -- 'awaiting_checkin_energy', 'awaiting_checkin_win', etc.
  data jsonb DEFAULT '{}'::jsonb,
  updated_at timestamptz DEFAULT now()
);

-- New table for chart data (generated by Gemini to avoid token overuse)
CREATE TABLE chart_data (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  chart_type text NOT NULL, -- 'entry_volume', 'energy_timeline', 'category_distribution', etc.
  period text NOT NULL, -- 'daily', 'weekly', 'monthly'
  data jsonb NOT NULL, -- Chart data points generated by Gemini
  generated_at timestamptz DEFAULT now(),
  expires_at timestamptz DEFAULT (now() + interval '24 hours'), -- Cache for 24 hours
  user_id uuid
);

-- Create indexes for better query performance
CREATE INDEX idx_entries_created_at ON entries(created_at DESC);
CREATE INDEX idx_entries_type ON entries(type);
CREATE INDEX idx_weekly_reports_week_start ON weekly_reports(week_start DESC);
CREATE INDEX idx_checkins_created_at ON checkins(created_at DESC);
CREATE INDEX idx_pattern_alerts_created_at ON pattern_alerts(created_at DESC);
CREATE INDEX idx_pattern_alerts_dismissed ON pattern_alerts(dismissed_at) WHERE dismissed_at IS NULL;
CREATE INDEX idx_chart_data_type_period ON chart_data(chart_type, period);
CREATE INDEX idx_chart_data_expires ON chart_data(expires_at);

-- RLS Policies (public for v1 - single user)
-- Enable RLS
ALTER TABLE entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE weekly_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE checkins ENABLE ROW LEVEL SECURITY;
ALTER TABLE pattern_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversation_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE chart_data ENABLE ROW LEVEL SECURITY;

-- Public access for v1 (replace with auth policies later)
CREATE POLICY "Allow all access to entries" ON entries
  FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow all access to weekly_reports" ON weekly_reports
  FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow all access to checkins" ON checkins
  FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow all access to pattern_alerts" ON pattern_alerts
  FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow all access to conversation_state" ON conversation_state
  FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow all access to chart_data" ON chart_data
  FOR ALL USING (true) WITH CHECK (true);

-- Weekly cron job (configure in Supabase dashboard or run this)
-- Note: Replace 'your-app.vercel.app' with your actual Vercel domain
-- This runs every Sunday at 8pm UTC
SELECT cron.schedule(
  'weekly-review-trigger',
  '0 20 * * 0',
  $$
  SELECT net.http_post(
    url := 'https://ramavarma-thampuran-ai.vercel.app/api/weekly-review',
    headers := '{"Content-Type": "application/json", "Authorization": "Bearer YOUR_SECRET_KEY"}'::jsonb,
    body := '{}'::jsonb
  ) AS request_id;
  $$
);

-- Daily pattern detection cron job (runs every day at 8pm UTC)
SELECT cron.schedule(
  'pattern-detection',
  '0 20 * * *',
  $$
  SELECT net.http_post(
    url := 'https://ramavarma-thampuran-ai.vercel.app/api/pattern-detection',
    headers := '{"Content-Type": "application/json"}'::jsonb
  ) AS request_id;
  $$
);

-- Daily chart data generation cron job (runs every day at 6am UTC)
SELECT cron.schedule(
  'chart-data-generation',
  '0 6 * * *',
  $$
  SELECT net.http_post(
    url := 'https://ramavarma-thampuran-ai.vercel.app/api/chart-data/generate',
    headers := '{"Content-Type": "application/json"}'::jsonb
  ) AS request_id;
  $$
);

-- View cron jobs
-- SELECT * FROM cron.job;

-- Unschedule if needed
-- SELECT cron.unschedule('weekly-review-trigger');
